CREATE DATABASE IF NOT EXISTS insetos_db;
USE insetos_db;

CREATE TABLE insetos (
    id_insetos INT AUTO_INCREMENT PRIMARY KEY,
    nome_insetos VARCHAR(50) NOT NULL,
    nc_insetos VARCHAR(50) NOT NULL,
    ordem_insetos VARCHAR(65) NOT NULL,
    longevidade_insetos DECIMAL(5, 1) NOT NULL,
    tamanho_insetos DECIMAL(5, 2) NOT NULL,
    familia_insetos VARCHAR(70) NOT NULL,
    dieta_insetos VARCHAR(50) NOT NULL,
    tem_asas BOOLEAN NOT NULL DEFAULT 0,
    destaque BOOLEAN NOT NULL DEFAULT 0,
    curisidade TEXT,
    foto_insetos TEXT
);

INSERT INTO insetos(nome_insetos, nc_insetos, ordem_insetos, longevidade_insetos, tamanho_insetos, familia_insetos, dieta_insetos, tem_asas, curisidade) VALUES
('Besouro Rinoceronte', 'Oryctes nasicornis', 'insetos', 3.0, 6.00, 'Scarabaeidae', 'Detritívoro', 1, 'Consegue levantar até 850 vezes o seu próprio peso, equivalente a um humano erguer vários carros.'),
('Besouro Hércules', 'Dynastes hercules', 'insetos', 0.5, 17.00, 'Scarabaeidae', 'Detritívoro', 1, 'É considerado um dos maiores insetoss do mundo e possui um chifre enorme usado para disputas territoriais.'),
('Besouro Rola Bosta', 'Scarabaeus sacer', 'insetos', 3.0, 3.00, 'Scarabaeidae', 'Coprófago', 1, 'Navega guiando se pela luz da Via Láctea para rolar suas bolas de esterco em linha reta.'),
('Besouro Golias', 'Goliathus goliatus', 'insetos', 1.0, 11.00, 'Scarabaeidae', 'Detritívoro', 1, 'Pode pesar mais de 100 gramas na fase larval, sendo um dos insetoss mais pesados da Terra.'),
('Besouro Elefante', 'Megasoma elephas', 'insetos', 0.3, 12.00, 'Scarabaeidae', 'Detritívoro', 1, 'Seu nome vem de seu grande porte e do chifre curvado que lembra a tromba de um elefante.'),
('Besouro Marmorado', 'Anomala dubia', 'insetos', 0.2, 1.50, 'Scarabaeidae', 'Herbívoro', 1, 'Suas larvas vivem enterradas no solo se alimentando de raízes em decomposição por meses.'),
('Besouro Verde das Flores', 'Cetonia aurata', 'insetos', 2.0, 2.00, 'Scarabaeidae', 'Nectarívoro', 1, 'Possui uma coloração metálica brilhante que confere camuflagem natural entre folhagens e pétalas.'),
('Besouro Atlas', 'Chalcosoma atlas', 'insetos', 0.7, 13.00, 'Scarabaeidae', 'Detritívoro', 1, 'Os machos usam seus chifres tridivididos para arremessar rivais para longe durante brigas por fêmeas.'),
('Besouro Ouro', 'Chrysina resplendens', 'insetos', 0.5, 3.00, 'Scarabaeidae', 'Herbívoro', 1, 'Sua carcaça brilha como ouro puro devido a estruturas microscópicas que refletem a luz.'),
('Besouro das Videiras', 'Pelidnota punctata', 'insetos', 1.0, 2.50, 'Scarabaeidae', 'Herbívoro', 1, 'Atrai se facilmente por luzes artificiais durante as noites quentes de verão.'),
('Besouro Violino', 'Mormolyce phyllodes', 'insetos', 1.5, 10.00, 'Carabidae', 'Carnívoro', 1, 'Possui um corpo extremamente achatado e alongado, adaptado para viver sob cascas finas de árvores.'),
('Besouro Bombardeiro', 'Brachinus crepitans', 'insetos', 1.0, 1.20, 'Carabidae', 'Carnívoro', 1, 'Dispara um jato químico fervendo a 100°C misturando compostos explosivos em seu abdômen.'),
('Besouro Caçador Dourado', 'Calosoma sycophanta', 'insetos', 2.0, 3.00, 'Carabidae', 'Carnívoro', 1, 'É um excelente predador de lagartas desfolhadoras, ajudando a controlar pragas florestais.'),
('Besouro Tigre Verde', 'Cicindela campestris', 'insetos', 1.0, 1.50, 'Carabidae', 'Carnívoro', 1, 'Corre tão rápido que precisa parar de enxergar temporariamente para processar as imagens visuais.'),
('Besouro Carabídeo Violeta', 'Carabus violaceus', 'insetos', 2.0, 3.00, 'Carabidae', 'Carnívoro', 1, 'Exala um odor defensivo forte e desagradável quando ameaçado por predadores.'),
('Besouro Corredor Noturno', 'Nebria brevicollis', 'insetos', 1.0, 1.20, 'Carabidae', 'Carnívoro', 1, 'Ativo durante a noite, caça ativamente aranhas e outros insetoss no solo da floresta.'),
('Besouro Tigre Praiano', 'Cicindela hybrida', 'insetos', 1.0, 1.60, 'Carabidae', 'Carnívoro', 1, 'Habita dunas de areia costeiras, onde caça pequenas presas com mandíbulas afiadas.'),
('Besouro Caçador Catarina', 'Calosoma inquisitor', 'insetos', 2.0, 2.20, 'Carabidae', 'Carnívoro', 1, 'Capaz de subir em copas de árvores para caçar lagartas vorazes que atacam carvalhos.'),
('Besouro Grão Negro', 'Harpalus rufipes', 'insetos', 1.5, 1.40, 'Carabidae', 'Onívoro', 1, 'Embora seja carnívoro, ocasionalmente consome sementes e grãos caídos no solo.'),
('Besouro Bombardeiro Gigante', 'Pheropsophus verticalis', 'insetos', 1.2, 2.00, 'Carabidae', 'Carnívoro', 1, 'Possui uma câmara de reação interna mais desenvolvida, permitindo múltiplos disparos químicos consecutivos.'),
('Besouro Sombrio de Cape', 'Circellium bacchus', 'insetos', 5.0, 4.50, 'Scarabaeidae', 'Coprófago', 0, 'Um dos poucos Besouros dung que adaptaram se perfeitamente a climas áridos sem voar.'),
('Besouro do Deserto de Namibe', 'Pachysoma striatum', 'insetos', 2.0, 3.00, 'Scarabaeidae', 'Detritívoro', 0, 'Recolhe umidade da neblina matinal usando ranhuras especiais em suas costas.'),
('Besouro Cadeia de Avis', 'Pachysoma denticolle', 'insetos', 1.5, 2.20, 'Scarabaeidae', 'Detritívoro', 0, 'Caminha por areias quentes do deserto em busca de detritos orgânicos levados pelo vento.'),
('Besouro Rola Bosta Caminhador', 'Scarabaeus ambiguus', 'insetos', 1.8, 2.80, 'Scarabaeidae', 'Coprófago', 0, 'Em vez de rolar, empurra esterco usando as pernas traseiras adaptadas como pás.'),
('Besouro do Deserto Coletor', 'Pachysoma hippocrates', 'insetos', 2.0, 2.70, 'Scarabaeidae', 'Detritívoro', 0, 'Suas patas curtas e robustas evitam que afunde na areia fofa durante o forrageamento.'),
('Escaravelho Sombrio de Richtersveld', 'Circellium morbillosum', 'insetos', 3.0, 3.20, 'Scarabaeidae', 'Coprófago', 0, 'Sobrevive a variações térmicas extremas em montanhas áridas da África do Sul.'),
('Besouro Rola Bosta Gordo', 'Eucranium arachnoides', 'insetos', 2.0, 2.00, 'Scarabaeidae', 'Coprófago', 0, 'Possui um abdômen abaulado que armazena reservas de gordura para períodos de escassez.'),
('Besouro Corredor das Pampas', 'Glyphoderus sterquilinus', 'insetos', 1.5, 1.80, 'Scarabaeidae', 'Coprófago', 0, 'Adapta se a campos abertos gramados, correndo rapidamente entre touceiras de capim.'),
('Besouro Escavador Siderus', 'Glyphoderus monticola', 'insetos', 1.8, 1.90, 'Scarabaeidae', 'Coprófago', 0, 'Cava galerias subterrâneas profundas para proteger sua fonte de alimento de outros insetoss.'),
('Besouro Caminhador Anactus', 'Anactus edentulus', 'insetos', 2.0, 2.10, 'Scarabaeidae', 'Detritívoro', 0, 'Usa seu exoesqueleto espesso para resistir à dessecação sob o sol escaldante.'),
('Besouro Caracol Carcaju', 'Cychrus caraboides', 'insetos', 2.0, 1.90, 'Carabidae', 'Carnívoro', 0, 'Suas mandíbulas estreitas são perfeitamente adaptadas para extrair lesmas de dentro de suas conchas.'),
('Besouro Terrestre Coriáceo', 'Carabus coriaceus', 'insetos', 3.0, 4.00, 'Carabidae', 'Carnívoro', 0, 'Um dos maiores Besouros terrestres da Europa, incapaz de voar devido aos élitros soldados.'),
('Besouro Cego das Cavernas', 'Anophthalmus hitleri', 'insetos', 1.5, 0.50, 'Carabidae', 'Carnívoro', 0, 'Vivendo na mais completa escuridão, perdeu os olhos e a pigmentação ao longo da evolução.'),
('Besouro Pedregal Gigante', 'Anthia thoracic', 'insetos', 2.0, 5.50, 'Carabidae', 'Carnívoro', 0, 'Possui glândulas de defesa potentes capazes de cuspir substâncias irritantes a distâncias curtas.'),
('Besouro Corredor Ibérico', 'Carabus rugosus', 'insetos', 2.0, 3.00, 'Carabidae', 'Carnívoro', 0, 'Possui coloração escura fosca que ajuda na absorção rápida de calor nas manhãs frias.'),
('Besouro Escavador Sombrio', 'Scarites buparius', 'insetos', 2.5, 4.20, 'Carabidae', 'Carnívoro', 0, 'Passa o dia escondido sob pedras grandes, saindo apenas na penumbra para caçar.'),
('Besouro Devorador de Lesmas', 'Carabus nemoralis', 'insetos', 2.0, 2.60, 'Carabidae', 'Carnívoro', 0, 'Aliado natural dos agricultores por controlar populações de moluscos pragas em hortas.'),
('Besouro Tigre Sem Asas', 'Manticora imperator', 'insetos', 3.0, 6.50, 'Carabidae', 'Carnívoro', 0, 'Um predador voraz e robusto de savanas secas, caçando com investidas rápidas e agressivas.'),
('Besouro Predador de Oito Pontos', 'Anthia sexguttata', 'insetos', 2.0, 4.00, 'Carabidae', 'Carnívoro', 0, 'Exibe marcações chamativas em seu corpo para alertar predadores sobre sua toxicidade.'),
('Besouro Terrestre Dourado', 'Carabus auratus', 'insetos', 2.0, 2.70, 'Carabidae', 'Carnívoro', 0, 'Brilha com tons metálicos iridescentes quando exposto à luz direta do sol.'),
('Louva a Deus Orquídea', 'Hymenopus coronatus', 'insetos', 0.7, 6.00, 'Hymenopodidae', 'Carnívoro', 1, 'Mimiciza perfeitamente uma flor de orquídea para atrair polinizadores inocentes direto para seu bote.'),
('Borboleta-monarca', 'Danaus plexippus', 'insetos', 10.0, 0.50, 'Nymphalidae', 'Herbívoro', 1, 'Famosa por sua migração multigeracional de milhares de quilômetros entre a América do Norte e o México.'),
('Abelha-europeia', 'Apis mellifera', 'insetos', 1.5, 0.10, 'Apidae', 'Nectarívoro', 1, 'Fundamental para a polinização de cultivos agrícolas e produção global de mel.'),
('Formiga-cortadeira', 'Atta cephalotes', 'insetos', 1.0, 0.05, 'Formicidae', 'Herbívoro', 0, 'Cortam pedaços de folhas para cultivar o fungo subterrâneo que serve de alimento para a colônia.'),
('Libélula-azul', 'Anax imperator', 'insetos', 8.0, 1.20, 'Aeshnidae', 'Carnívoro', 1, 'Ágil predadora aérea com uma taxa de sucesso de captura de presas superior a 90%.'),
('Joaninha de Sete Pontos', 'Coccinella septempunctata', 'insetos', 0.8, 0.02, 'Coccinellidae', 'Carnívoro', 1, 'insetos benéfico que consome vorazmente pulgões nas plantações.'),
('Gafanhoto-migratório', 'Locusta migratoria', 'insetos', 6.0, 2.00, 'Acrididae', 'Herbívoro', 1, 'Capaz de se reunir em grandes enxames destrutivos que devastam plantações inteiras.'),
('Vaga-lume Comum', 'Photinus pyralis', 'insetos', 1.2, 0.03, 'Lampyridae', 'Carnívoro', 1, 'Produz luz fria através de bioluminescência abdominal para atrair parceiros sexuais.'),
('Bicho-pau Gigante', 'Extatosoma tiaratum', 'insetos', 15.0, 15.00, 'Phasmatidae', 'Herbívoro', 0, 'Mestre supremo da camuflagem que se parece perfeitamente com folhas secas e espinhosas.'),
('Cigarra-comum', 'Lyristes plebejus', 'insetos', 4.5, 1.50, 'Cicadidae', 'Herbívoro', 1, 'Emite um som estridente característico através de membranas chamadas timbales.'),
('Mariposa-luna', 'Actias luna', 'insetos', 11.0, 0.80, 'Saturniidae', 'Herbívoro', 1, 'Mariposa noturna de coloração verde translúcida que não possui boca na fase adulta.'),
('Mosca-varejeira', 'Calliphora vicina', 'insetos', 1.0, 0.04, 'Calliphoridae', 'Detritívoro', 1, 'Importante na decomposição de matéria orgânica e em investigações forenses.'),
('Percevejo-verde', 'Nezara viridula', 'insetos', 1.5, 0.08, 'Pentatomidae', 'Herbívoro', 1, 'Libera um odor defensivo forte e desagradável quando ameaçado ou manuseado.'),
('Tesourinha-comum', 'Forficula auricularia', 'insetos', 1.8, 0.05, 'Forficulidae', 'Omnívoro', 1, 'Reconhecida pelos cercos em forma de pinça na extremidade do abdome.'),
('Louva-a-deus comum', 'Mantis religiosa', 'insetos', 7.0, 0.40, 'Mantidae', 'Carnívoro', 1, 'Predador de emboscada paciente com excelente visão estereoscópica.'),
('Abelha-carpintaria', 'Xylocopa virginica', 'insetos', 2.5, 0.60, 'Apidae', 'Nectarívoro', 1, 'Fura a madeira para construir seus ninhos em galerias complexas.'),
('Pulga-dos-gatos', 'Ctenocephalides felis', 'insetos', 0.2, 0.001, 'Pulicidae', 'Hematófago', 0, 'Ectoparasita sem asas capaz de saltar dezenas de vezes o seu próprio comprimento.'),
('Barata-americana', 'Periplaneta americana', 'insetos', 4.0, 1.20, 'Blattidae', 'Detritívoro', 1, 'insetos noturno extremamente resistente e rápido, adaptado a ambientes urbanos.'),
('Cupim-subterrâneo', 'Coptotermes formosanus', 'insetos', 0.6, 0.01, 'Rhinotermitidae', 'Herbívoro', 0, 'Vive em colônias complexas com castas especializadas e consome celulose de madeira.'),
('Vespa-mandarina', 'Vespa mandarinia', 'insetos', 5.0, 1.50, 'Vespidae', 'Carnívoro', 1, 'A maior espécie de vespa do mundo, conhecida por ataques devastadores a colmeias de abelhas.'),
('insetos-folha', 'Phyllium bioculatum', 'insetos', 8.0, 2.50, 'Phylliidae', 'Herbívoro', 0, 'Mimetiza folhas verdes com veias e texturas tão perfeitas que enganam predadores visuais.'),

('Caranguejeira Rosa', 'Grammostola rosea', 'Aracnídeos', 15.0, 15.0, 'Theraphosidae', 'Carnívoro', 1, 'Aranha dócil nativa do Chile.'),
('Aranha Golias', 'Theraphosa blondi', 'Aracnídeos', 30.0, 175.0, 'Theraphosidae', 'Carnívoro', 1, 'A maior aranha do mundo.'),
('Tarântula de Joelhos Vermelhos', 'Brachypelma smithi', 'Aracnídeos', 14.0, 15.0, 'Theraphosidae', 'Carnívoro', 1, 'Famosa pelas listras laranjas.'),
('Viúva Negra', 'Latrodectus mactans', 'Aracnídeos', 3.8, 1.0, 'Theridiidae', 'Carnívoro', 1, 'Veneno neurotóxico potente.'),
('Aranha Marrom', 'Loxosceles reclusa', 'Aracnídeos', 2.0, 0.5, 'Sicariidae', 'Carnívoro', 1, 'Veneno necrosante perigoso.'),
('Armadeira', 'Phoneutria nigriventer', 'Aracnídeos', 15.0, 10.0, 'Ctenidae', 'Carnívoro', 1, 'Agressiva e venenosa.'),
('Aranha Saltadora Zebra', 'Salticus scenicus', 'Aracnídeos', 0.7, 0.1, 'Salticidae', 'Carnívoro', 1, 'Pula grandes distâncias.'),
('Aranha Pescadora', 'Dolomedes tenebrosus', 'Aracnídeos', 8.0, 2.0, 'Pisauridae', 'Carnívoro', 1, 'Caça na superfície da água.'),
('Aranha Lobo', 'Lycosa tarantula', 'Aracnídeos', 3.0, 1.5, 'Lycosidae', 'Carnívoro', 1, 'Caça correndo no solo.'),
('Aranha Caranguejo', 'Misumena vatia', 'Aracnídeos', 1.0, 0.2, 'Thomisidae', 'Carnívoro', 1, 'Camufla-se em flores.'),
('Escorpião Amarelo', 'Tityus serrulatus', 'Aracnídeos', 7.0, 2.0, 'Buthidae', 'Carnívoro', 1, 'Muito perigoso no Brasil.'),
('Escorpião Imperador', 'Pandinus imperator', 'Aracnídeos', 20.0, 30.0, 'Scorpionidae', 'Carnívoro', 1, 'Gigante de garras grossas.'),
('Escorpião Negro', 'Tityus bahiensis', 'Aracnídeos', 6.0, 1.8, 'Buthidae', 'Carnívoro', 1, 'Tronco escuro e pernas claras.'),
('Escorpião Dourado', 'Leiurus quinquestriatus', 'Aracnídeos', 9.0, 3.5, 'Buthidae', 'Carnívoro', 1, 'Veneno altamente letal.'),
('Escorpião do Deserto', 'Hadrurus arizonensis', 'Aracnídeos', 14.0, 8.0, 'Caraboctonidae', 'Carnívoro', 1, 'O maior da América do Norte.'),
('Carrapato Estrela', 'Amblyomma cajennense', 'Aracnídeos', 1.0, 0.1, 'Ixodidae', 'Hematófago', 1, 'Transmite febre maculosa.'),
('Carrapato de Boi', 'Rhipicephalus microplus', 'Aracnídeos', 0.8, 0.08, 'Ixodidae', 'Hematófago', 1, 'Praga na pecuária.'),
('Ácaro da Poeira', 'Dermatophagoides pteronyssinus', 'Aracnídeos', 0.03, 0.01, 'Pyroglyphidae', 'Detritívoro', 1, 'Vive em colchões.'),
('Ácaro da Sarna', 'Sarcoptes scabiei', 'Aracnídeos', 0.04, 0.01, 'Sarcoptidae', 'Parasita', 1, 'Escava a pele humana.'),
('Ácaro Vermelho', 'Trombidium holosericeum', 'Aracnídeos', 0.4, 0.01, 'Trombidiidae', 'Carnívoro', 1, 'Pelagem vermelha aveludada.'),
('Opilião Comum', 'Phalangium opilio', 'Aracnídeos', 8.0, 0.2, 'Phalangiidae', 'Onívoro', 1, 'Pernas muito finas e longas.'),
('Opilião Espinhoso', 'Acanthopachylus aculeatus', 'Aracnídeos', 4.0, 0.8, 'Gonyleptidae', 'Onívoro', 1, 'Possui espinhos defensivos.'),
('Opilião Cavernícola', 'Gongylobelus sp.', 'Aracnídeos', 5.0, 0.15, 'Gongyleptidae', 'Onívoro', 1, 'Vive em cavernas escuras.'),
('Opilião Laranja', 'Vonones sayi', 'Aracnídeos', 0.6, 0.05, 'Cosmetidae', 'Onívoro', 1, 'Cor chamativa e odor forte.'),
('Amblipígio Gigante', 'Acanthophrynus coronatus', 'Aracnídeos', 20.0, 5.0, 'Phrynidae', 'Carnívoro', 1, 'Assustador, mas sem veneno.'),
('Aranha Chicote', 'Phrynus marginemaculatus', 'Aracnídeos', 10.0, 2.0, 'Phrynidae', 'Carnívoro', 1, 'Usa pernas como antenas.'),
('Aranha Camelo', 'Galeodes arabs', 'Aracnídeos', 15.0, 8.0, 'Galeodidae', 'Carnívoro', 1, 'Corre rápido no deserto.'),
('Vinagrinho', 'Mastigoproctus giganteus', 'Aracnídeos', 15.0, 10.0, 'Thelyphonidae', 'Carnívoro', 1, 'Dispara ácido acético.'),
('Aranha Teia de Funil', 'Atrax robustus', 'Aracnídeos', 5.0, 3.0, 'Atracidae', 'Carnívoro', 1, 'Mortal da Austrália.'),
('Tarântula Azul', 'Cyriopagopus lividus', 'Aracnídeos', 13.0, 10.0, 'Theraphosidae', 'Carnívoro', 1, 'Pernas de azul brilhante.'),
('Tarântula Metálica', 'Poecilotheria metallica', 'Aracnídeos', 15.0, 12.0, 'Theraphosidae', 'Carnívoro', 1, 'Arborícola ameaçada.'),
('Aranha Espinhosa', 'Gasteracantha cancriformis', 'Aracnídeos', 1.0, 0.3, 'Araneidae', 'Carnívoro', 1, 'Abdômen com espinhos.'),
('Aranha de Jardim', 'Argiope aurantia', 'Aracnídeos', 2.8, 0.5, 'Araneidae', 'Carnívoro', 1, 'Teia em formato de zig-zag.'),
('Caranguejeira Baboon', 'Pelinobius muticus', 'Aracnídeos', 20.0, 30.0, 'Theraphosidae', 'Carnívoro', 1, 'Cava tocas no Quênia.'),
('Escorpião de Cauda Grossa', 'Androctonus australis', 'Aracnídeos', 10.0, 5.0, 'Buthidae', 'Carnívoro', 1, 'Letal do norte da África.'),
('Escorpião de Casca', 'Centruroides sculpturatus', 'Aracnídeos', 7.0, 1.5, 'Buthidae', 'Carnívoro', 1, 'Escala paredes.'),
('Pseudoescorpião', 'Chelifer cancroides', 'Aracnídeos', 0.4, 0.05, 'Cheliferidae', 'Carnívoro', 1, 'Come ácaros em livros antigos.'),
('Palpígrado', 'Eukoenenia mirabilis', 'Aracnídeos', 0.1, 0.01, 'Eukoeneniidae', 'Carnívoro', 1, 'Micro-aracnídeo de solo.'),
('Carrapato de Cervo', 'Ixodes scapularis', 'Aracnídeos', 0.3, 0.02, 'Ixodidae', 'Hematófago', 1, 'Vetor da doença de Lyme.'),
('Ácaro Aranha', 'Tetranychus urticae', 'Aracnídeos', 0.05, 0.01, 'Tetranychidae', 'Herbívoro', 1, 'Praga agrícola que tece teias.'),
('Ricínuleo', 'Ricinoides atewa', 'Aracnídeos', 1.0, 0.1, 'Ricinoididae', 'Carnívoro', 1, 'Parece um carrapato blindado.'),
('Solífugo Dourado', 'Eremobates pallipes', 'Aracnídeos', 5.0, 2.0, 'Eremobatidae', 'Carnívoro', 1, 'Caça lagartos à noite.'),
('Aranha Espadachim', 'Dysdera crocata', 'Aracnídeos', 1.5, 0.4, 'Dysderidae', 'Carnívoro', 1, 'Caçadora de tatuzinhos.'),
('Aranha Cuspidora', 'Scytodes thoracica', 'Aracnídeos', 0.6, 0.1, 'Scytodidae', 'Carnívoro', 1, 'Cospe teia venenosa.'),
('Tarântula Tigre', 'Poecilotheria tigrinawesseli', 'Aracnídeos', 14.0, 10.0, 'Theraphosidae', 'Carnívoro', 1, 'Padrão listrado.'),
('Escorpião Listrado', 'Centruroides vittatus', 'Aracnídeos', 6.0, 1.2, 'Buthidae', 'Carnívoro', 1, 'Comum no Texas.'),
('Caranguejeira Veludo Negro', 'Grammostola pulchra', 'Aracnídeos', 16.0, 18.0, 'Theraphosidae', 'Carnívoro', 1, 'Totalmente preta e mansa.'),
('Tarântula Esqueleto', 'Ephebopus murinus', 'Aracnídeos', 12.0, 9.0, 'Theraphosidae', 'Carnívoro', 1, 'Pernas lembram ossos.'),
('Caranguejeira Caranguejo', 'Acanthoscurria geniculata', 'Aracnídeos', 20.0, 25.0, 'Theraphosidae', 'Carnívoro', 1, 'Faixas brancas nas pernas.'),
('Opilião Lenhador', 'Leiobunum rotundum', 'Aracnídeos', 10.0, 0.1, 'Sclerosomatidae', 'Onívoro', 1, 'Aglomera-se em troncos.'),
('Ácaro de Foliculo', 'Demodex folliculorum', 'Aracnídeos', 0.03, 0.01, 'Demodicidae', 'Detritívoro', 1, 'Vive nos poros do rosto.'),
('Carrapato de Galinha', 'Argas persicus', 'Aracnídeos', 0.6, 0.04, 'Argasidae', 'Hematófago', 1, 'Carrapato mole de aves.'),
('Opilião Gigante', 'Trogulus tricarinatus', 'Aracnídeos', 2.0, 0.3, 'Trogulidae', 'Onívoro', 1, 'Cobre-se de terra.'),
('Aranha d Água', 'Argyroneta aquatica', 'Aracnídeos', 1.5, 0.5, 'Cybaeidae', 'Carnívoro', 1, 'Constrói sino de ar embaixo d água.'),
('Aranha Lince', 'Peucetia viridans', 'Aracnídeos', 2.0, 0.6, 'Oxyopidae', 'Carnívoro', 1, 'Pernas cheias de espinhos.'),
('Aranha Caçadora', 'Heteropoda venatoria', 'Aracnídeos', 12.0, 3.0, 'Sparassidae', 'Carnívoro', 1, 'Gigante e rápida nas paredes.'),
('Aranha Gladiadora', 'Deinopis subrufa', 'Aracnídeos', 2.5, 0.8, 'Deinopidae', 'Carnívoro', 1, 'Joga a teia como uma rede.'),
('Escorpião de Caverna', 'Typhlochactas mitchelli', 'Aracnídeos', 2.0, 0.5, 'Typhlochactidae', 'Carnívoro', 1, 'Cego e vive nas trevas.'),
('Amblipígio das Cavernas', 'Charinus cavernicolus', 'Aracnídeos', 5.0, 1.0, 'Charinidae', 'Carnívoro', 1, 'Totalmente cego.'),
('Solífugo Gigante', 'Solpuga venosa', 'Aracnídeos', 12.0, 9.0, 'Solpugidae', 'Carnívoro', 1, 'Mordida dilacera presas.'),
('Aranha de Pelúcia', 'Eresus sandaliatus', 'Aracnídeos', 1.0, 0.2, 'Eresidae', 'Carnívoro', 1, 'Macho vermelho com pintas pretas.'),

('Caranguejo Ermitão', 'Pagurus bernhardus', 'Crustáceos', 5.0, 30.0, 'Paguridae', 'Detritívoro', 1, 'Mora em conchas vazias.'),
('Caranguejo Aranha Gigante', 'Macrocheira kaempferi', 'Crustáceos', 380.0, 19000.0, 'Inachidae', 'Onívoro', 1, 'O maior artrópode do mundo.'),
('Caranguejo Uçá', 'Ucides cordatus', 'Crustáceos', 8.0, 200.0, 'Ucididae', 'Herbívoro', 1, 'Vive nos manguezais do Brasil.'),
('Siri Azul', 'Callinectes sapidus', 'Crustáceos', 20.0, 450.0, 'Portunidae', 'Onívoro', 1, 'Possui nadadeiras traseiras fortes.'),
('Caranguejo Fantasma', 'Ocypode quadrata', 'Crustáceos', 5.0, 50.0, 'Ocypodidae', 'Detritívoro', 1, 'Corre muito rápido na areia.'),
('Lagosta Suada', 'Panulirus argus', 'Crustáceos', 60.0, 7000.0, 'Palinuridae', 'Carnívoro', 1, 'Não possui pinças grandes.'),
('Lagosta Americana', 'Homarus americanus', 'Crustáceos', 100.0, 20000.0, 'Nephropidae', 'Carnívoro', 1, 'Garras esmagadoras gigantes.'),
('Camarão Limpador', 'Lysmata amboinensis', 'Crustáceos', 6.0, 5.0, 'Hippolytidae', 'Onívoro', 1, 'Limpa parasitas de peixes.'),
('Camarão Pistola', 'Alpheus heterochaelis', 'Crustáceos', 5.0, 10.0, 'Alpheidae', 'Carnívoro', 1, 'Gera bolha sônica que atordoa.'),
('Tamarutaca', 'Odontodactylus scyllarus', 'Crustáceos', 18.0, 100.0, 'Odontodactylidae', 'Carnívoro', 1, 'Soco mais rápido do oceano.'),
('Tatuzinho de Jardim', 'Armadillidium vulgare', 'Crustáceos', 1.5, 1.0, 'Armadillidiidae', 'Detritívoro', 1, 'Enrola-se como uma bola.'),
('Isópode Gigante', 'Bathynomus giganteus', 'Crustáceos', 35.0, 1700.0, 'Cirolanidae', 'Detritívoro', 1, 'Devorador do fundo do mar.'),
('Craca Bolota', 'Balanus glandula', 'Crustáceos', 2.0, 5.0, 'Balanidae', 'Filtrador', 1, 'Gruda em rochas e navios.'),
('Krill Antártico', 'Euphausia superba', 'Crustáceos', 6.0, 2.0, 'Euphausiidae', 'Filtrador', 1, 'Base da teia alimentar do gelo.'),
('Caranguejo dos Coqueiros', 'Birgus latro', 'Crustáceos', 40.0, 4100.0, 'Coenobitidae', 'Onívoro', 1, 'Sobe em árvores e quebra cocos.'),
('Camarão Rosa', 'Penaeus paulensis', 'Crustáceos', 20.0, 40.0, 'Penaeidae', 'Detritívoro', 1, 'Muito consumido na culinária.'),
('Caranguejo Chama-Maré', 'Uca pugnax', 'Crustáceos', 3.0, 15.0, 'Ocypodidae', 'Detritívoro', 1, 'Macho tem uma garra gigante.'),
('Caranguejo Yeti', 'Kiwa hirsuta', 'Crustáceos', 15.0, 300.0, 'Kiwaidae', 'Carnívoro', 1, 'Garras peludas no fundo do mar.'),
('Lagosta Boxeadora', 'Enoplometopus debelius', 'Crustáceos', 12.0, 80.0, 'Enoplometopidae', 'Carnívoro', 1, 'Pequena lagosta de recife.'),
('Camarão Imperador', 'Periclimenes imperator', 'Crustáceos', 2.0, 1.0, 'Palaemonidae', 'Onívoro', 1, 'Pega carona em pepinos do mar.'),
('Siri Candeia', 'Portunus pelagicus', 'Crustáceos', 15.0, 250.0, 'Portunidae', 'Carnívoro', 1, 'Siri nadador muito ágil.'),
('Lagostim Vermelho', 'Procambarus clarkii', 'Crustáceos', 12.0, 50.0, 'Cambaridae', 'Onívoro', 1, 'Lagostim de água doce resistente.'),
('Camarão Bailarino', 'Rhynchocinetes durbanensis', 'Crustáceos', 4.0, 3.0, 'Rhynchocinetidae', 'Detritívoro', 1, 'Movimento de dança na água.'),
('Pulga da Areia', 'Talitrus saltator', 'Crustáceos', 2.0, 0.5, 'Talitridae', 'Detritívoro', 1, 'Pula nas praias à noite.'),
('Copépode Comum', 'Calanus finmarchicus', 'Crustáceos', 0.4, 0.01, 'Calanidae', 'Filtrador', 1, 'Microcrustáceo planctônico.'),
('Caranguejo Decorador', 'Camposcia retusa', 'Crustáceos', 10.0, 50.0, 'Inachidae', 'Onívoro', 1, 'Cola algas no corpo para camuflagem.'),
('Caranguejo Vampiro', 'Geosesarma dennerle', 'Crustáceos', 2.0, 10.0, 'Sesarmidae', 'Carnívoro', 1, 'Cores roxas e olhos amarelos.'),
('Baratinha da Praia', 'Ligia oceanica', 'Crustáceos', 3.0, 2.0, 'Ligiidae', 'Detritívoro', 1, 'Corre pelas pedras na maré baixa.'),
('Camarão Arlequim', 'Hymenocera picta', 'Crustáceos', 5.0, 15.0, 'Hymenoceridae', 'Carnívoro', 1, 'Caça exclusivamente estrelas do mar.'),
('Percebe', 'Pollicipes pollicipes', 'Crustáceos', 5.0, 20.0, 'Pollicipedidae', 'Filtrador', 1, 'Craca com pedúnculo comestível.'),
('Caranguejo Caleidoscópio', 'Gecarcoidea natalis', 'Crustáceos', 11.0, 400.0, 'Gecarcinidae', 'Herbívoro', 1, 'Faz a marcha vermelha em Christmas Island.'),
('Camarão de Poça', 'Palaemon serratus', 'Crustáceos', 10.0, 8.0, 'Palaemonidae', 'Onívoro', 1, 'Transparente com listras.'),
('Caranguejo Boxeador', 'Lybia tessellata', 'Crustáceos', 2.5, 12.0, 'Xanthidae', 'Onívoro', 1, 'Segura anêmonas nas garras para defesa.'),
('Lagosta Sapateira', 'Scyllarides latus', 'Crustáceos', 30.0, 1500.0, 'Scyllaridae', 'Onívoro', 1, 'Sem garras, formato achatado.'),
('Siri da Lama', 'Scylla serrata', 'Crustáceos', 25.0, 3000.0, 'Portunidae', 'Carnívoro', 1, 'Vive enterrado no lodo.'),
('Caranguejo Fiddler', 'Uca tangeri', 'Crustáceos', 4.0, 20.0, 'Ocypodidae', 'Detritívoro', 1, 'Agita a garra para cortejar.'),
('Isópode da Madeira', 'Porcellio scaber', 'Crustáceos', 1.5, 1.0, 'Porcellionidae', 'Detritívoro', 1, 'Vive embaixo de troncos podres.'),
('Lagostim Azul', 'Cherax destructor', 'Crustáceos', 20.0, 150.0, 'Parastacidae', 'Onívoro', 1, 'Garras fortes e cor azulada.'),
('Artêmia', 'Artemia salina', 'Crustáceos', 1.5, 0.1, 'Artemiidae', 'Filtrador', 1, 'Sobrevive em lagos super salgados.'),
('Pulga d Água', 'Daphnia pulex', 'Crustáceos', 0.5, 0.01, 'Daphniidae', 'Filtrador', 1, 'Nativa de águas doces paradas.'),
('Camarão Sangue', 'Lysmata debelius', 'Crustáceos', 5.0, 8.0, 'Hippolytidae', 'Onívoro', 1, 'Vermelho forte com pintas brancas.'),
('Caranguejo Azul Terrestre', 'Cardisoma guanhumi', 'Crustáceos', 15.0, 500.0, 'Gecarcinidae', 'Herbívoro', 1, 'Escava tocas na restinga.'),
('Caranguejo Dourado', 'Chaceon fenneri', 'Crustáceos', 20.0, 1000.0, 'Geryonidae', 'Carnívoro', 1, 'Vive em grandes profundidades.'),
('Lagosta de Água Doce', 'Astacus astacus', 'Crustáceos', 15.0, 100.0, 'Astacidae', 'Onívoro', 1, 'Espécie europeia ameaçada.'),
('Caranguejo-Rei', 'Paralithodes camtschaticus', 'Crustáceos', 180.0, 12000.0, 'Lithodidae', 'Carnívoro', 1, 'Altamente comercializado no Alasca.'),
('Camarão Bambu', 'Atyopsis moluccensis', 'Crustáceos', 10.0, 15.0, 'Atyidae', 'Filtrador', 1, 'Usa patas em forma de leque para filtrar água.'),
('Caranguejo Japonês', 'Chionoecetes opilio', 'Crustáceos', 90.0, 1500.0, 'Oregoniidae', 'Onívoro', 1, 'Caranguejo das neves.'),
('Caranguejo-Aranha Decorador', 'Oregonia gracilis', 'Crustáceos', 4.0, 10.0, 'Oregoniidae', 'Onívoro', 1, 'Parece uma alga andante.'),
('Craca Gigante', 'Austromegabalanus psittacus', 'Crustáceos', 30.0, 500.0, 'Balanidae', 'Filtrador', 1, 'Comestível na costa chilena.'),
('Isópode Parasita', 'Cymothoa exigua', 'Crustáceos', 3.0, 5.0, 'Cymothoidae', 'Parasita', 1, 'Substitui a língua de peixes.'),
('Lagosta Pintada', 'Panulirus versicolor', 'Crustáceos', 40.0, 1200.0, 'Palinuridae', 'Carnívoro', 1, 'Coloração vibrante em recifes.'),
('Siri-Boia', 'Arenaeus cribrarius', 'Crustáceos', 12.0, 100.0, 'Portunidae', 'Carnívoro', 1, 'Comum em praias brasileiras.'),
('Caranguejo-Pedra', 'Menippe mercenaria', 'Crustáceos', 15.0, 800.0, 'Menippidae', 'Carnívoro', 1, 'Possui pinças esmagadoras massivas.'),
('Camarão Tigre Gigante', 'Penaeus monodon', 'Crustáceos', 33.0, 130.0, 'Penaeidae', 'Detritívoro', 1, 'Muito criado em cativeiro.'),
('Camarão Sete-Barbas', 'Xiphopenaeus kroyeri', 'Crustáceos', 10.0, 20.0, 'Penaeidae', 'Detritívoro', 1, 'Comum no litoral sudeste brasileiro.'),
('Caranguejo de Galápagos', 'Grapsus grapsus', 'Crustáceos', 8.0, 150.0, 'Grapsidae', 'Herbívoro', 1, 'Colorido e anda pelas pedras vulcânicas.'),
('Camarão Fantasma', 'Palaemonetes paludosus', 'Crustáceos', 4.0, 2.0, 'Palaemonidae', 'Detritívoro', 1, 'Totalmente transparente.'),
('Lagosta de Lama', 'Thalassina anomala', 'Crustáceos', 25.0, 400.0, 'Thalassinidae', 'Detritívoro', 1, 'Constrói montes de lama no mangue.'),
('Caranguejo Bola', 'Ilia nucleus', 'Crustáceos', 3.0, 15.0, 'Leucosiidae', 'Detritívoro', 1, 'Carapaça perfeitamente esférica.'),
('Anfípode Cego', 'Niphargus', 'Crustáceos', 2.0, 0.5, 'Niphargidae', 'Onívoro', 1, 'Vive em lençóis freáticos.'),
('Camarão Nariz-de-Agulha', 'Farfantepenaeus subtilis', 'Crustáceos', 15.0, 30.0, 'Penaeidae', 'Detritívoro', 1, 'Possui rostro alongado.'),

('Caracol de Jardim', 'Cornu aspersum', 'Moluscos', 4.0, 15.0, 'Helicidae', 'Herbívoro', 1, 'Deixa um rastro de muco por onde passa.'),
('Caramujo Gigante Africano', 'Lissachatina fulica', 'Moluscos', 20.0, 500.0, 'Achatinidae', 'Herbívoro', 1, 'Praga invasora devoradora de hortas.'),
('Polvo Comum', 'Octopus vulgaris', 'Moluscos', 90.0, 9000.0, 'Octopodidae', 'Carnívoro', 1, 'Extremamente inteligente e mestre em camuflagem.'),
('Lula Colossal', 'Mesonychoteuthis hamiltoni', 'Moluscos', 1400.0, 490000.0, 'Cranchiidae', 'Carnívoro', 1, 'Possui ganchos nos tentáculos.'),
('Lula Gigante', 'Architeuthis dux', 'Moluscos', 1200.0, 275000.0, 'Architeuthidae', 'Carnívoro', 1, 'O olho é do tamanho de um prato.'),
('Ostra do Pacífico', 'Magallana gigas', 'Moluscos', 15.0, 100.0, 'Ostreidae', 'Filtrador', 1, 'Cultivada no mundo todo para consumo.'),
('Mexilhão Dourado', 'Limnoperna fortunei', 'Moluscos', 4.0, 10.0, 'Mytilidae', 'Filtrador', 1, 'Invasor de rios sul-americanos.'),
('Náutilo', 'Nautilus pompilius', 'Moluscos', 20.0, 1500.0, 'Nautilidae', 'Carnívoro', 1, 'Fóssil vivo com concha em espiral.'),
('Choco', 'Sepia officinalis', 'Moluscos', 49.0, 4000.0, 'Sepiidae', 'Carnívoro', 1, 'Possui osso interno e muda de textura.'),
('Polvo de Anéis Azuis', 'Hapalochlaena maculosa', 'Moluscos', 20.0, 40.0, 'Octopodidae', 'Carnívoro', 1, 'Pequeno mas com veneno mortal.'),
('Polvo Mímico', 'Thaumoctopus mimicus', 'Moluscos', 60.0, 1000.0, 'Octopodidae', 'Carnívoro', 1, 'Imita peixes venenosos e serpentes.'),
('Polvo Dumbo', 'Grimpoteuthis', 'Moluscos', 20.0, 500.0, 'Opisthoteuthidae', 'Carnívoro', 1, 'Nadas com abas que lembram orelhas.'),
('Lesma do Mar Dragão Azul', 'Glaucus atlanticus', 'Moluscos', 3.0, 5.0, 'Glaucidae', 'Carnívoro', 1, 'Flutua de cabeça para baixo comendo caravelas.'),
('Bailarina Espanhola', 'Hexabranchus sanguineus', 'Moluscos', 40.0, 200.0, 'Hexabranchidae', 'Carnívoro', 1, 'Nada ondulando feito uma saia flamenca.'),
('Lesma Leopardo', 'Limax maximus', 'Moluscos', 20.0, 30.0, 'Limacidae', 'Onívoro', 1, 'Acasala pendurada por um fio de muco.'),
('Caracol Cone', 'Conus geographus', 'Moluscos', 15.0, 100.0, 'Conidae', 'Carnívoro', 1, 'Dispara um arpão de veneno fatal.'),
('Lula Vampira', 'Vampyroteuthis infernalis', 'Moluscos', 30.0, 500.0, 'Vampyroteuthidae', 'Detritívoro', 1, 'Vira do avesso para se proteger.'),
('Marisco', 'Mytilus edulis', 'Moluscos', 10.0, 30.0, 'Mytilidae', 'Filtrador', 1, 'Comum em costões rochosos.'),
('Vieira', 'Pecten maximus', 'Moluscos', 15.0, 200.0, 'Pectinidae', 'Filtrador', 1, 'Foge nadando abrindo e fechando a concha.'),
('Ostra Perlífera', 'Pinctada margaritifera', 'Moluscos', 20.0, 500.0, 'Pteriidae', 'Filtrador', 1, 'Produz pérolas negras valiosas.'),
('Berbigão', 'Cerastoderma edule', 'Moluscos', 5.0, 15.0, 'Cardiidae', 'Filtrador', 1, 'Vive enterrado na areia de praias.'),
('Caramujo Trombeta', 'Charonia tritonis', 'Moluscos', 50.0, 2000.0, 'Charoniidae', 'Carnívoro', 1, 'Predador da estrela-do-mar coroa-de-espinhos.'),
('Polvo do Coco', 'Amphioctopus marginatus', 'Moluscos', 15.0, 300.0, 'Octopodidae', 'Carnívoro', 1, 'Usa cascas de coco como escudo.'),
('Aruá do Mato', 'Megalobulimus', 'Moluscos', 15.0, 150.0, 'Megalobulimidae', 'Herbívoro', 1, 'Caracol nativo gigante das florestas brasileiras.'),
('Caramujo Maçã', 'Pomacea maculata', 'Moluscos', 15.0, 100.0, 'Ampullariidae', 'Herbívoro', 1, 'Bota ovos rosas fora da água.'),
('Lesma do Mar Ovelhinha', 'Costasiella kuroshimae', 'Moluscos', 0.5, 0.5, 'Costasiellidae', 'Herbívoro', 1, 'Faz fotossíntese com algas que engole.'),
('Lula Voadora', 'Todarodes pacificus', 'Moluscos', 50.0, 500.0, 'Ommastrephidae', 'Carnívoro', 1, 'Salta para fora da água planar longas distâncias.'),
('Siba Chocante', 'Metasepia pfefferi', 'Moluscos', 8.0, 50.0, 'Sepiidae', 'Carnívoro', 1, 'Anda pelo fundo do mar e exibe cores pulsantes.'),
('Búzio', 'Bulla striata', 'Moluscos', 3.0, 10.0, 'Bullidae', 'Herbívoro', 1, 'Concha lisa comum em colares.'),
('Caramujo de Aquário', 'Neritina natalensis', 'Moluscos', 2.5, 5.0, 'Neritidae', 'Herbívoro', 1, 'Excelente devorador de algas em vidros.'),
('Argonauta', 'Argonauta argo', 'Moluscos', 20.0, 300.0, 'Argonautidae', 'Carnívoro', 1, 'Fêmea cria uma concha fina para ovos.'),
('Lula de Vidro', 'Cranchia scabra', 'Moluscos', 15.0, 100.0, 'Cranchiidae', 'Carnívoro', 1, 'Totalmente transparente para sumir na luz.'),
('Chiton', 'Chiton tuberculatus', 'Moluscos', 8.0, 30.0, 'Chitonidae', 'Herbívoro', 1, 'Concha feita de 8 placas sobrepostas.'),
('Lesma do Mar Pikachu', 'Thecacera pacifica', 'Moluscos', 2.0, 3.0, 'Polyceridae', 'Carnívoro', 1, 'Amarela com pontas pretas.'),
('Bivalve Gigante', 'Tridacna gigas', 'Moluscos', 120.0, 200000.0, 'Cardiidae', 'Filtrador', 1, 'Pode pesar 200 kg nos recifes de coral.'),
('Bredo', 'Ensis directus', 'Moluscos', 17.0, 40.0, 'Pharidae', 'Filtrador', 1, 'Concha reta como uma navalha.'),
('Lesma Banana', 'Ariolimax columbianus', 'Moluscos', 25.0, 115.0, 'Ariolimacidae', 'Herbívoro', 1, 'Amarela brilhante das florestas úmidas.'),
('Caracol Assassino', 'Clea helena', 'Moluscos', 2.0, 3.0, 'Buccinidae', 'Carnívoro', 1, 'Usado em aquários para comer outros caracóis.'),
('Ostra do Mangue', 'Crassostrea rhizophorae', 'Moluscos', 8.0, 50.0, 'Ostreidae', 'Filtrador', 1, 'Gruda nas raízes do mangue.'),
('Caracol de Fogo', 'Platymma tweediei', 'Moluscos', 7.0, 25.0, 'Chronidae', 'Onívoro', 1, 'Corpo vermelho vibrante e concha preta.'),
('Polvo Pigmeu', 'Octopus wolfi', 'Moluscos', 2.5, 1.0, 'Octopodidae', 'Carnívoro', 1, 'O menor polvo conhecido.'),
('Lula-Lagalume', 'Watasenia scintillans', 'Moluscos', 7.0, 15.0, 'Enoploteuthidae', 'Carnívoro', 1, 'Brilha forte no escuro para atrair presas.'),
('Pé-de-Pelicano', 'Aporrhais pespelecani', 'Moluscos', 5.0, 15.0, 'Aporrhaidae', 'Onívoro', 1, 'Concha com pontas que lembram patas.'),
('Concha da Lua', 'Polinices', 'Moluscos', 6.0, 40.0, 'Naticidae', 'Carnívoro', 1, 'Perfura outras conchas com ácido.'),
('Lesma-do-mar Alface', 'Elysia crispata', 'Moluscos', 5.0, 10.0, 'Plakobranchidae', 'Herbívoro', 1, 'Corpo ondulado que rouba cloroplastos.'),
('Escafópode', 'Antalis vulgaris', 'Moluscos', 4.0, 5.0, 'Dentaliidae', 'Detritívoro', 1, 'Concha em forma de dente de elefante.'),
('Polvo Cobertor', 'Tremoctopus violaceus', 'Moluscos', 200.0, 10000.0, 'Tremoctopodidae', 'Carnívoro', 1, 'Abre uma grande rede de pele para intimidar.'),
('Sépia Faraó', 'Sepia pharaonis', 'Moluscos', 43.0, 5000.0, 'Sepiidae', 'Carnívoro', 1, 'Textura e cor espetaculares.'),
('Caracol Terrestre Ibérico', 'Otala lactea', 'Moluscos', 3.0, 10.0, 'Helicidae', 'Herbívoro', 1, 'Consumido como escargot.'),
('Abre-Fecha', 'Spondylus', 'Moluscos', 15.0, 300.0, 'Spondylidae', 'Filtrador', 1, 'Concha cheia de espinhos longos.'),
('Lula-de-Humboldt', 'Dosidicus gigas', 'Moluscos', 150.0, 50000.0, 'Ommastrephidae', 'Carnívoro', 1, 'Agressiva e caça em grandes bandos.'),
('Caramujo de Areia', 'Nassarius', 'Moluscos', 2.0, 4.0, 'Nassariidae', 'Detritívoro', 1, 'Sai da areia quando sente cheiro de carniça.'),
('Búzios-Cobra', 'Cypraea tigris', 'Moluscos', 10.0, 80.0, 'Cypraeidae', 'Onívoro', 1, 'Concha super polida com pintas.'),
('Polvo das Fontes Termais', 'Vulcanoctopus hydrothermalis', 'Moluscos', 15.0, 50.0, 'Octopodidae', 'Carnívoro', 1, 'Vive perto de vulcões submarinos.'),
('Mexilhão-Zebra', 'Dreissena polymorpha', 'Moluscos', 3.0, 5.0, 'Dreissenidae', 'Filtrador', 1, 'Grave praga de dutos industriais.'),
('Lesma Nua', 'Deroceras reticulatum', 'Moluscos', 3.5, 5.0, 'Agriolimacidae', 'Herbívoro', 1, 'Praga agrícola que devora mudas.'),
('Nudibrânquio Pijama', 'Chromodoris quadricolor', 'Moluscos', 5.0, 10.0, 'Chromodorididae', 'Carnívoro', 1, 'Listras azuis, brancas e laranjas.'),
('Caracol-Pintado', 'Liguus fasciatus', 'Moluscos', 5.0, 20.0, 'Orthalicidae', 'Herbívoro', 1, 'Conchas coloridas arborícolas da Flórida.'),
('Teredo', 'Teredo navalis', 'Moluscos', 20.0, 15.0, 'Teredinidae', 'Xilófago', 1, 'Cupim do mar, fura cascos de madeira.'),
('Anjo do Mar', 'Clione limacina', 'Moluscos', 5.0, 0.05, 'Clionidae', 'Carnívoro', 1, 'Molusco pelágico transparente que parece flutuar com asas.'),
('Caramujo-Babosa', 'Physella acuta', 'Moluscos', 1.5, 2.0, 'Physidae', 'Detritívoro', 1, 'Caramujo de água doce comum em aquários.'),

('Água-viva-da-lua', 'Aurelia aurita', 'Cnidário', 25.0, 150.0, 'Ulmaridae', 'Carnívoro', 1, 'Possui quatro braços orais transparentes e um formato de guarda-chuva com margens tentaculares.'),
('Caravela-portuguesa', 'Physalia physalis', 'Cnidário', 30.0, 250.0, 'Physaliidae', 'Carnívoro', 1, 'Organismo colonial flutuante com tentáculos longos e altamente venenosos.'),
('Anêmona-do-mar comum', 'Actinia equina', 'Cnidário', 7.0, 30.0, 'Actiniidae', 'Carnívoro', 0, 'Fixa-se a rochas costeiras e retrai seus tentáculos vermelhos quando exposta à maré baixa.'),
('Água-viva-juba-de-leão', 'Cyanea capillata', 'Cnidário', 200.0, 2000.0, 'Cyaneidae', 'Carnívoro', 1, 'A maior espécie de água-viva do mundo, com centenas de tentáculos finos e longos.'),
('Coral-cérebro', 'Meandrina meandrites', 'Cnidário', 50.0, 5000.0, 'Meandrinidae', 'Carnívoro', 0, 'Coral construtor de recifes com sulcos sinuosos que lembram a textura de um cérebro.'),
('Vespa-do-mar', 'Chironex fleckeri', 'Cnidário', 30.0, 2000.0, 'Chirodropidae', 'Carnívoro', 1, 'Uma das criaturas mais venenosas do planeta, encontrada nas águas costeiras do Indo-Pacífico.'),
('Hydra verde', 'Hydra viridissima', 'Cnidário', 1.0, 0.01, 'Hydridae', 'Carnívoro', 0, 'Pequeno pólipo de água doce que vive fixo a vegetação aquática e possui simetria radial.'),
('Coral-chifre-de-alce', 'Acropora palmata', 'Cnidário', 100.0, 4000.0, 'Acroporidae', 'Carnívoro', 0, 'Coral ramificado essencial para a proteção das costas contra tempestades tropicais.'),
('Anêmona-gigante-de-carpetes', 'Stichodactyla gigantea', 'Cnidário', 50.0, 1500.0, 'Stichodactylidae', 'Carnívoro', 0, 'Abriga peixes-palhaço em simbiose mútua contra predadores marinhos.'),
('Água-viva-de-cabeça-de-cogumelo', 'Rhizostoma pulmo', 'Cnidário', 40.0, 1200.0, 'Rhizostomatidae', 'Carnívoro', 1, 'Frequente no Mar Mediterrâneo, alimenta-se filtrando plâncton com seus braços fundidos.'),
('Coral-fogo', 'Millepora alcicornis', 'Cnidário', 30.0, 800.0, 'Milleporidae', 'Carnívoro', 0, 'Hidrocoral urticante que causa forte sensação de queimadura ao toque humano.'),
('Água-viva-luminosa', 'Pelagia noctiluca', 'Cnidário', 10.0, 80.0, 'Pelagiidae', 'Carnívoro', 1, 'Emite forte luz azulada quando perturbada mecanicamente na escuridão do oceano.'),
('Caneta-do-mar', 'Pennatula phosphorea', 'Cnidário', 20.0, 45.0, 'Pennatulidae', 'Carnívoro', 0, 'Colônia de pólipos que se assemelha a uma antiga pena de escrita fincada no sedimento.'),
('Coral-sol', 'Tubastraea coccinea', 'Cnidário', 15.0, 200.0, 'Dendrophylliidae', 'Carnívoro', 0, 'Espécie invasora no litoral brasileiro, reconhecida por seus pólipos de coloração amarela intensa.'),
('Anêmona-sol', 'Condylactis gigantea', 'Cnidário', 25.0, 300.0, 'Actiniidae', 'Carnívoro', 0, 'Exibe tentáculos longos com pontas bulbosas vibrantes que variam do verde ao roxo.'),
('Água-viva-imortal', 'Turritopsis dohrnii', 'Cnidário', 0.5, 0.02, 'Oceaniidae', 'Carnívoro', 1, 'Capaz de reverter seu ciclo de vida celular após atingir a maturidade, teoricamente imortal.'),
('Coral-mão-de-morto', 'Alcyonium digitatum', 'Cnidário', 20.0, 300.0, 'Alcyoniidae', 'Carnívoro', 0, 'Coral mole de águas frias com lóbulos carnudos que lembram dedos humanos.'),
('Velella', 'Velella velella', 'Cnidário', 5.0, 0.5, 'Porpitidae', 'Carnívoro', 1, 'Pequena colônia flutuante dotada de uma crista triangular que atua como vela ao vento.'),
('Anêmona-tubo', 'Cerianthus membranaceus', 'Cnidário', 40.0, 600.0, 'Cerianthidae', 'Carnívoro', 0, 'Constrói um tubo membranoso no sedimento arenoso de onde projeta seus longos tentáculos.'),
('Coral-cogumelo', 'Fungia fungites', 'Cnidário', 15.0, 250.0, 'Fungiidae', 'Carnívoro', 0, 'Coral solitário em forma de disco que descansa livremente sobre o substrato arenoso.'),
('Água-viva-caçadora', 'Chiropsalmus quadrumana', 'Cnidário', 15.0, 300.0, 'Chirodropidae', 'Carnívoro', 1, 'Cubozoário com tentáculos dispostos em cachos nos cantos de sua umbrella cúbica.'),
('Coral-preto', 'Antipathes dichotoma', 'Cnidário', 150.0, 3000.0, 'Antipathidae', 'Carnívoro', 0, 'Possui esqueleto córneo escuro muito utilizado historicamente na fabricação de joias.'),
('Anêmona-verde-gigante', 'Anthopleura xanthogrammica', 'Cnidário', 30.0, 800.0, 'Actiniidae', 'Carnívoro', 0, 'Deve sua cor verde vibrante a algas fotossintéticas simbióticas que habitam seus tecidos.'),
('Água-viva-de-ponto-azul', 'Mastigias papua', 'Cnidário', 18.0, 350.0, 'Mastigiidae', 'Carnívoro', 1, 'Abriga algas zooxantelas que lhe fornecem energia através da luz solar.'),
('Coral-de-fogo-comum', 'Millepora complanata', 'Cnidário', 40.0, 1100.0, 'Milleporidae', 'Carnívoro', 0, 'Forma lâminas verticais calcárias em recifes rasos e expostos à forte arrebentação.'),
('Anêmona-das-rochas', 'Bunodosoma caissorum', 'Cnidário', 8.0, 40.0, 'Actiniidae', 'Carnívoro', 0, 'Espécie comum no litoral brasileiro com verrugas adesivas pelo corpo.'),
('Água-viva-japonesa', 'Nemopilema nomurai', 'Cnidário', 150.0, 150000.0, 'Stomolophidae', 'Carnívoro', 1, 'Gigante dos mares asiáticos que causa enormes prejuízos à pesca comercial.'),
('Coral-estrela', 'Montastraea cavernosa', 'Cnidário', 60.0, 6000.0, 'Faviidae', 'Carnívoro', 0, 'Forma colônias massivas com cálices profundos e bem demarcados na superfície.'),
('Anêmona-elegante', 'Anthopleura elegantissima', 'Cnidário', 6.0, 25.0, 'Actiniidae', 'Carnívoro', 0, 'Conhecida por formar colônias clonais que travam batalhas territoriais usando tentáculos especializados.'),
('Água-viva-crucifixe', 'Haliclystus auricula', 'Cnidário', 3.0, 2.0, 'Staurozoa', 'Carnívoro', 0, 'Estauromedusa séssil que se fixa a algas marinhas por um pedúnculo basal.'),
('Coral-tubular-amarelo', 'Tubastraea micrantha', 'Cnidário', 50.0, 2500.0, 'Dendrophylliidae', 'Carnívoro', 0, 'Forma arbustos densos com ramificações escuras e pólipos amarelos brilhantes.'),
('Anêmona-cavalo', 'Actinia fragacea', 'Cnidário', 8.0, 45.0, 'Actiniidae', 'Carnívoro', 0, 'Apresenta manchas verdes distintas ao longo de sua base carnuda vermelha.'),
('Água-viva-bombardeira', 'Periphylla periphylla', 'Cnidário', 20.0, 400.0, 'Periphyllidae', 'Carnívoro', 1, 'Espécie de profundidade com coloração marrom-avermelhada escura e bioluminescência.'),
('Coral-chifre-de-cervo-falso', 'Acropora cervicornis', 'Cnidário', 120.0, 4500.0, 'Acroporidae', 'Carnívoro', 0, 'Crescimento rápido em forma de galhos cilíndricos pontiagudos.'),
('Anêmona-borboleta', 'Aiptasia pallida', 'Cnidário', 4.0, 5.0, 'Aiptasiidae', 'Carnívoro', 0, 'Comum em aquários marinhos, considerada praga devido à sua rápida proliferação clonal.'),
('Água-viva-diamante', 'Chirodropus pragmaticus', 'Cnidário', 25.0, 1500.0, 'Chirodropidae', 'Carnívoro', 1, 'Cubomedusa predadora com potentes toxinas neurotóxicas em seus tentáculos.'),
('Coral-couve-flor', 'Pocillopora damicornis', 'Cnidário', 20.0, 400.0, 'Pocilloporidae', 'Carnívoro', 0, 'Possui ramificações curtas e compactas que lembram a cabeça de uma couve-flor.'),
('Anêmona-de-fogo', 'Actinodendron arboreum', 'Cnidário', 15.0, 180.0, 'Actinodendridae', 'Carnívoro', 0, 'Seus tentáculos lembram galhos de árvores e liberam toxinas severas ao toque.'),
('Água-viva-coroa', 'Atolla wyvillei', 'Cnidário', 10.0, 100.0, 'Atollidae', 'Carnívoro', 1, 'Emite um impressionante show de luzes azuladas em anel quando atacada no abismo marinho.'),
('Coral-abano-do-mar', 'Gorgonia ventalina', 'Cnidário', 80.0, 1200.0, 'Gorgoniidae', 'Carnívoro', 0, 'Gorgônia em formato de leque plano que se posiciona perpendicularmente às correntes.'),
('Anêmona-magnífica', 'Heteractis magnifica', 'Cnidário', 45.0, 2000.0, 'Stichodactylidae', 'Carnívoro', 0, 'Uma das principais espécies hospedeiras para peixes-palhaço em recifes tropicais.'),
('Água-viva-azul', 'Cyanea lamarckii', 'Cnidário', 30.0, 500.0, 'Cyaneidae', 'Carnívoro', 1, 'Água-viva translúcida com tons azulados encontrada nas águas temperadas europeias.'),
('Coral-colunar', 'Porites astreoides', 'Cnidário', 40.0, 3000.0, 'Poritidae', 'Carnívoro', 0, 'Forma massas encrustantes ou nodulares com coloração amarelada marcante.'),
('Anêmona-pescadora', 'Tealia felina', 'Cnidário', 12.0, 150.0, 'Urticinidae', 'Carnívoro', 0, 'Revestida por cascalho e detritos aderidos ao seu corpo pegajoso para camuflagem.'),
('Água-viva-de-fogo-africana', 'Rhopilema nomadica', 'Cnidário', 50.0, 4000.0, 'Rhizostomatidae', 'Carnívoro', 1, 'Espécie invasora migratória no Mar Mediterrâneo com picadas dolorosas.'),
('Coral-dedo', 'Porites porites', 'Cnidário', 25.0, 800.0, 'Poritidae', 'Carnívoro', 0, 'Forma aglomerados de ramos curtos e grossos semelhantes a dedos grossos.'),
('Anêmona-imperador', 'Condylactis aurantiaca', 'Cnidário', 20.0, 250.0, 'Actiniidae', 'Carnívoro', 0, 'Possui tentáculos translúcidos com pontas coloridas contrastantes.'),
('Água-viva-cruciforme-gigante', 'Stauromedusa geniculata', 'Cnidário', 4.0, 3.0, 'Staurozoa', 'Carnívoro', 0, 'Forma séssil incomum que habita águas frias do norte.'),
('Coral-formigueiro', 'Madracis mirabilis', 'Cnidário', 30.0, 900.0, 'Pocilloporidae', 'Carnívoro', 0, 'Forma colônias densas de ramos finos e pontiagudos em águas mais profundas.'),
('Anêmona-listrada', 'Diadumene lineata', 'Cnidário', 2.5, 2.0, 'Haliplanellidae', 'Carnívoro', 0, 'Pequena anêmona invasora global com colônias marcadas por listras verticais verdes e brancas.'),
('Água-viva-lanterninha', 'Aequorea victoria', 'Cnidário', 12.0, 80.0, 'Aequoreidae', 'Carnívoro', 1, 'Famosa na biologia molecular pela proteína verde fluorescente (GFP) extraída de seus tecidos.'),
('Coral-tubo-verde', 'Clavularia viridis', 'Cnidário', 15.0, 150.0, 'Clavulariidae', 'Carnívoro', 0, 'Coral mole incrustante com pólipos que se assemelham a pequenas margaridas verdes brilhantes.'),
('Anêmona-tapete', 'Stichodactyla haddoni', 'Cnidário', 40.0, 1800.0, 'Stichodactylidae', 'Carnívoro', 0, 'Habita fundos arenosos rasos, enterrando sua base e expandindo seu disco adesivo na superfície.'),
('Água-viva-cauda-de-cavalo', 'Dactylometra quinquecirrha', 'Cnidário', 25.0, 400.0, 'Pelagiidae', 'Carnívoro', 1, 'Apresenta linhas marrons radiais na umbrella e tentáculos longos urticantes.'),
('Coral-bola-de-neve', 'Scolymia cubensis', 'Cnidário', 8.0, 100.0, 'Mussidae', 'Carnívoro', 0, 'Coral solitário com pólipo grande e carnoso exibindo cores fluorescentes sob luz azul.'),
('Anêmona-pedunculada', 'Alicia mirabilis', 'Cnidário', 15.0, 90.0, 'Aliciidae', 'Carnívoro', 0, 'Possui verrugas ramificadas cheias de nematocistos venenosos ao longo de sua coluna.'),
('Água-viva-comum-do-atlântico', 'Drymonema dalmatinum', 'Cnidário', 60.0, 3000.0, 'Drymonematidae', 'Carnívoro', 1, 'Predadora voraz de outras águas-vivas, alcançando tamanhos impressionantes.'),
('Coral-alface', 'Undaria tenuifolia', 'Cnidário', 30.0, 600.0, 'Agariciidae', 'Carnívoro', 0, 'Suas colônias formam lâminas finas e onduladas que lembram folhas de alface dobradas.'),
('Anêmona-de-vidro', 'Exaiptasia diaphana', 'Cnidário', 3.0, 3.0, 'Aiptasiidae', 'Carnívoro', 0, 'Possui corpo translúcido e delgado, amplamente estudada em pesquisas de simbiose.'),
('Água-viva-púrpura', 'Chrysaora hysosella', 'Cnidário', 30.0, 500.0, 'Pelagiidae', 'Carnívoro', 1, 'Reconhecida pelas listras em forma de V marrons ou púrpuras em sua umbrella.'),
('Coral-bambu', 'Isidis hippuris', 'Cnidário', 60.0, 1200.0, 'Isididae', 'Carnívoro', 0, 'Coral de profundidade com esqueleto segmentado em nós calcários e entrenós proteicos.'),
    
('Estrela-do-mar comum', 'Asterias rubens', 'Equinodermo', 20.0, 80.0, 'Asteriidae', 'Carnívoro', 1, 'Predadora voraz de moluscos bivalves, abrindo suas conchas com os pés ambulacrários.'),
('Oriço-do-mar roxo', 'Strongylocentrotus purpuratus', 'Equinodermo', 7.0, 150.0, 'Echinidae', 'Herbívoro', 1, 'Usa sua poderosa boca com mandíbulas (lanterna-de-aristóteles) para raspar algas das rochas.'),
('Pepino-do-mar comum', 'Holothuria tubulosa', 'Equinodermo', 25.0, 300.0, 'Holothuriidae', 'Detritívoro', 1, 'Ingere sedimentos marinhos para filtrar matéria orgânica nutritiva no fundo do oceano.'),
('Estrela-do-mar coroa-de-espinhos', 'Acanthaster planci', 'Equinodermo', 40.0, 1200.0, 'Acanthasteridae', 'Carnívoro', 1, 'Especializada em se alimentar de pólipos de corais vivos, podendo causar desequilíbrios em recifes.'),
('Oriço-do-mar negro', 'Diadema antillarum', 'Equinodermo', 10.0, 250.0, 'Diadematidae', 'Herbívoro', 1, 'Possui espinhos finos e longos extremamente venenosos que protegem recifes de supercrescimento de algas.'),
('Estrela-do-mar azul', 'Linckia laevigata', 'Equinodermo', 30.0, 200.0, 'Ophidiasteridae', 'Carnívoro', 1, 'Apresenta coloração azul celeste marcante e regenera-se facilmente de fragmentos corporais.'),
('Ofiúro frágil', 'Ophiothrix fragilis', 'Equinodermo', 10.0, 15.0, 'Ophiotrichidae', 'Detritívoro', 1, 'Braços longos e flexíveis que se movem em serpenteando velozmente pelo substrato.'),
('Lírio-do-mar', 'Antedon bifida', 'Equinodermo', 15.0, 25.0, 'Antedonidae', 'Suspensívoro', 1, 'Crinoide séssil ou de movimentos lentos que lembra uma flor delicada com braços plumosos.'),
('Bolacha-da-praia', 'Echinarachnius parma', 'Equinodermo', 8.0, 40.0, 'Scutellidae', 'Detritívoro', 1, 'Equinodermo plano achatado em forma de moeda que vive enterrado em bancos de areia.'),
('Estrela-girassol', 'Pycnopodia helianthoides', 'Equinodermo', 100.0, 5000.0, 'Asteriidae', 'Carnívoro', 1, 'Uma das maiores estrelas do mar do mundo, com dezenas de braços ágeis e vorazes.'),
('Pepino-do-mar leopardo', 'Bohadschia argus', 'Equinodermo', 50.0, 1500.0, 'Holothuriidae', 'Detritívoro', 1, 'Exibe manchas oculares características em seu corpo cilíndrico robusto.'),
('Oriço-lápis', 'Heterocentrotus mammillatus', 'Equinodermo', 12.0, 400.0, 'Echinometridae', 'Herbívoro', 1, 'Possui espinhos grossos e maciços em forma de lápis que resistem a fortes ondas.'),
('Estrela-almofada', 'Oreaster reticulatus', 'Equinodermo', 40.0, 1800.0, 'Oreasteridae', 'Carnívoro', 1, 'Estrela robusta com corpo abaulado e textura reticulada rígida.'),
('Ofiúro-gigante-de-cesto', 'Gorgonocephalus eucnemis', 'Equinodermo', 70.0, 800.0, 'Gorgonocephalidae', 'Suspensívoro', 1, 'Seus braços ramificados complexos formam uma rede para capturar plâncton nas correntes profundas.'),
('Pepino-do-mar-ananas', 'Thelenota ananas', 'Equinodermo', 60.0, 2500.0, 'Stichopodidae', 'Detritívoro', 1, 'Possui projeções cutâneas protuberantes que lembram a casca texturizada de um abacaxi.'),
('Oriço-do-mar verde', 'Strongylocentrotus droebachiensis', 'Equinodermo', 6.0, 90.0, 'Strongylocentrotidae', 'Herbívoro', 1, 'Habita águas frias do norte, alimentando-se avidamente de algas kelp.'),
('Estrela-do-mar-de-sangue', 'Henricia leviuscula', 'Equinodermo', 12.0, 40.0, 'Echinasteridae', 'Carnívoro', 1, 'Coloração vermelha ou alaranjada viva, comum em poças de maré rochosas.'),
('Oriço-tóxico', 'Toxopneustes pileolus', 'Equinodermo', 15.0, 500.0, 'Toxopneustidae', 'Herbívoro', 1, 'Equipado com pedicelárias em forma de flor capazes de injetar toxinas dolorosas.'),
('Estrela-batida', 'Patiria miniata', 'Equinodermo', 15.0, 100.0, 'Asterinidae', 'Carnívoro', 1, 'Membranas interbraquiais estendidas dão um aspecto de estrela encorpada.'),
('Pepino-do-mar-espinhoso', 'Apostichopus californicus', 'Equinodermo', 40.0, 1200.0, 'Stichopodidae', 'Detritívoro', 1, 'Importante espécie comercializada na Ásia pela sua textura e valor medicinal.'),
('Ofiúro verde', 'Ophiocoma scolopendrina', 'Equinodermo', 15.0, 25.0, 'Ophiocomidae', 'Detritívoro', 1, 'Ativo durante a noite, estende seus braços de fendas rochosas para coletar detritos.'),
('Oriço-do-mar branco', 'Tripneustes gratilla', 'Equinodermo', 10.0, 300.0, 'Toxopneustidae', 'Herbívoro', 1, 'Costuma camuflar-se cobrindo o corpo com pedaços de algas e conchas.'),
('Estrela-de-areia', 'Archaster typicus', 'Equinodermo', 12.0, 50.0, 'Archasteridae', 'Detritívoro', 1, 'Vive semi-enterrada na areia rasa de praias tropicais protegidas.'),
('Pepino-do-mar preto', 'Holothuria atra', 'Equinodermo', 30.0, 600.0, 'Holothuriidae', 'Detritívoro', 1, 'Revestido por uma camada de muco que frequentemente retém grãos de areia escura.'),
('Oriço-do-mar de rocha', 'Paracentrotus lividus', 'Equinodermo', 7.0, 120.0, 'Echinidae', 'Herbívoro', 1, 'Capaz de escavar cavidades em rochas calcárias duras usando seus dentes e espinhos.'),
('Estrela-cometa', 'Linckia guildingi', 'Equinodermo', 25.0, 150.0, 'Ophidiasteridae', 'Carnívoro', 1, 'Conhecida por se reproduzir assexuadamente por fissão e regeneração de braços isolados.'),
('Ofiúro reticulado', 'Ophionereis reticulata', 'Equinodermo', 12.0, 20.0, 'Ophionereididae', 'Detritívoro', 1, 'Possui um padrão de rede geométrica delicada na superfície dorsal do disco central.'),
('Lírio-do-mar plumoso', 'Comaster schlegelii', 'Equinodermo', 20.0, 35.0, 'Comasteridae', 'Suspensívoro', 1, 'Possui dezenas de braços plumosos coloridos que capturam plâncton na correnteza.'),
('Bolacha-da-praia-gigante', 'Dendraster excentricus', 'Equinodermo', 10.0, 60.0, 'Dendrasteridae', 'Detritívoro', 1, 'Forma densos leitos verticais em fundos arenosos expostos às ondas.'),
('Estrela-fragilizada-vermelha', 'Ophioderma brevispinum', 'Equinodermo', 10.0, 18.0, 'Ophiodermatidae', 'Detritívoro', 1, 'Disco central robusto com braços curtos e grossos que se movem de forma serpentina.'),
('Pepino-do-mar-amarelo', 'Cucumaria frondosa', 'Equinodermo', 20.0, 400.0, 'Cucumariidae', 'Suspensívoro', 1, 'Estende tentáculos orais ramificados em forma de árvore para filtrar alimento da água.'),
('Oriço-do-mar coração', 'Echinocardium cordatum', 'Equinodermo', 6.0, 50.0, 'Loveniidae', 'Detritívoro', 1, 'Possui simetria bilateral secundária e vive profundamente enterrado no sedimento arenoso.'),
('Estrela-das-profundidades', 'Bathybiaster vexillifer', 'Equinodermo', 25.0, 150.0, 'Benthopectinidae', 'Carnívoro', 1, 'Habita regiões abissais frias alimentando-se de detritos e pequenos invertebrados.'),
('Pepino-do-mar vermelho', 'Parastichopus parvimensis', 'Equinodermo', 25.0, 350.0, 'Stichopodidae', 'Detritívoro', 1, 'Exibe coloração avermelhada com tubérculos proeminentes e alimenta-se de matéria orgânica.'),
('Ofiúro de espinhos longos', 'Ophiothrix spiculata', 'Equinodermo', 8.0, 10.0, 'Ophiotrichidae', 'Detritívoro', 1, 'Possui espinhos transparentes e espinhosos ao longo de seus longos braços.'),
('Oriço-diadema-austral', 'Centrostephanus coronatus', 'Equinodermo', 9.0, 200.0, 'Diadematidae', 'Herbívoro', 1, 'Encontrado em recifes rochosos, possui espinhos longos e escuros com anéis.'),
('Estrela-de-porcelana', 'Fromia monilis', 'Equinodermo', 10.0, 30.0, 'Ophidiasteridae', 'Carnívoro', 1, 'Apresenta placas coloridas contrastantes que lembram peças de mosaico de porcelana.'),
('Pepino-do-mar gigante cinza', 'Stichopus chloronotus', 'Equinodermo', 35.0, 900.0, 'Stichopodidae', 'Detritívoro', 1, 'Corpo verde-escuro alongado com papilas dorsais pontiagudas.'),
('Lírio-do-mar de coral', 'Cenometra bella', 'Equinodermo', 15.0, 20.0, 'Colobometridae', 'Suspensívoro', 1, 'Vive empoleirado em gorgônias e corais em busca de correntes ricas em plâncton.'),
('Oriço-do-mar de fogo', 'Asthenosoma varium', 'Equinodermo', 12.0, 250.0, 'Echinothuriidae', 'Herbívoro', 1, 'Possui testas flexíveis e espinhos ocos venenosos muito perigosos.'),
('Estrela-do-mar-de-rasteiro', 'Leptasterias polaris', 'Equinodermo', 25.0, 300.0, 'Asteriidae', 'Carnívoro', 1, 'Estrela friorentas que incuba seus ovos diretamente sob o corpo em vez de liberá-los na água.'),
('Pepino-do-mar-dragão', 'Synapta maculata', 'Equinodermo', 200.0, 3000.0, 'Synaptidae', 'Detritívoro', 1, 'Pepino serpenteiforme extremamente longo que carece de pés ambulacrários locomotores tradicionais.'),
('Oriço-do-mar verde-escuro', 'Echinometra lucunter', 'Equinodermo', 6.0, 80.0, 'Echinometridae', 'Herbívoro', 1, 'Comum na zona intertidal rochosa brasileira, adaptado a fortes impactos de ondas.'),
('Estrela-alvinegra', 'Nardoa tuberculata', 'Equinodermo', 20.0, 120.0, 'Ophidiasteridae', 'Carnívoro', 1, 'Apresenta tubérculos arredondados distribuídos ao longo de seus braços roliços.'),
('Ofiúro malhado', 'Ophiolepis paucispina', 'Equinodermo', 4.0, 2.0, 'Ophiolepididae', 'Detritívoro', 1, 'Pequeno ofiúro que habita fendas em recifes de coral rasos.'),
('Pepino-do-mar marrom', 'Holothuria forskali', 'Equinodermo', 30.0, 500.0, 'Holothuriidae', 'Detritívoro', 1, 'Capaz de ejetar fios pegajosos de Cuvier quando severamente ameaçado por predadores.'),
('Oriço-do-mar do mediterrâneo', 'Sphaerechinus granularis', 'Equinodermo', 12.0, 350.0, 'Toxopneustidae', 'Herbívoro', 1, 'Possui espinhos curtos e grossos com pontas arroxeadas ou brancas.'),
('Estrela-do-mar espinhosa do atlântico', 'Marthasterias glacialis', 'Equinodermo', 35.0, 400.0, 'Asteriidae', 'Carnívoro', 1, 'Grandes espinhos cônicos dispostos em três fileiras ao longo de cada braço.'),
('Lírio-do-mar elegante', 'Tropometra carinata', 'Equinodermo', 12.0, 15.0, 'Tropometridae', 'Suspensívoro', 1, 'Espécie tropical que se agarra a corais e rochas em águas de forte correnteza.'),
('Pepino-do-mar marinho amarelo-escuro', 'Colochirus robustus', 'Equinodermo', 10.0, 60.0, 'Cucumariidae', 'Suspensívoro', 1, 'Exibe coloração amarela ou laranja viva com tentáculos ramificados vistosos.'),
('Oriço-do-mar violeta', 'Arbacia lixula', 'Equinodermo', 6.0, 100.0, 'Arbaciidae', 'Herbívoro', 1, 'Reconhecido por sua coloração preta ou roxa escura profunda e carapaça nua no ápice.'),
('Estrela-de-pintas-laranja', 'Fromia indica', 'Equinodermo', 8.0, 25.0, 'Ophidiasteridae', 'Carnívoro', 1, 'Pequena estrela com corpo avermelhado e manchas laranja contrastantes.'),
('Pepino-do-mar espinhento marrom', 'Actinopyga mauritiana', 'Equinodermo', 40.0, 1400.0, 'Holothuriidae', 'Detritívoro', 1, 'Habita recifes rasos de águas turbulentas, alimentando-se de areia rica emnutrientes.'),
('Ofiúro de braços listrados', 'Ophiocoma wendtii', 'Equinodermo', 12.0, 20.0, 'Ophiocomidae', 'Detritívoro', 1, 'Possui células em sua pele que funcionam como lentes ópticas naturais, agindo como um olho composto'),
('Oriço-do-mar australiano', 'Heliocidaris erythrogramma', 'Equinodermo', 9.0, 200.0, 'Echinometridae', 'Herbívoro', 1, 'Endêmico da Austrália, com espinhos curtos de tons avermelhados ou esverdeados.'),
('Estrela-do-mar roxa do pacífico', 'Pisaster ochraceus', 'Equinodermo', 25.0, 500.0, 'Asteriidae', 'Carnívoro', 1, 'Espécie-chave em ecossistemas de poças de maré na costa oeste norte-americana.'),
('Pepino-do-mar roxo-escuro', 'Pseudocolochirus violaceus', 'Equinodermo', 12.0, 80.0, 'Cucumariidae', 'Suspensívoro', 1, 'Apresenta tentáculos orais ramificados de cor violeta brilhante para captação de plâncton'),
('Oriço-do-mar perfurador', 'Echinometra mathaei', 'Equinodermo', 5.0, 60.0, 'Echinometridae', 'Herbívoro', 1, 'Amplamente distribuído no Indo-Pacífico, abriga-se em rochas calcárias erodidas.'),
('Estrela-do-mar de areia fina', 'Astropecten aranciacus', 'Equinodermo', 45.0, 600.0, 'Astropectinidae', 'Carnívoro', 1, 'Estrela de areia com margens pectinadas, caçadora noturna de moluscos e vermes.'),
('Ofiúro de braços longos', 'Amphipholis squamata', 'Equinodermo', 3.0, 1.0, 'Amphiuridae', 'Detritívoro', 1, 'Pequeno ofiúro cosmopolita que incuba seus ovos internamente até a eclosão.'),
('Lírio-do-mar gigante de fenda', 'Lamprometra palmata', 'Equinodermo', 25.0, 45.0, 'Mariametridae', 'Suspensívoro', 1, 'Crinoide tropical com múltiplos braços flexíveis que formam leques filtradores.');
    
    UPDATE insetos SET foto_insetoss = 'https://cdn.questlog.gg/crimson desert/assets/_sprites/itemicon_prefab_cd_m0006_00_rhinocerosbeetle_00_0001.webp' WHERE id_insetoss = 1;
    UPDATE insetos SET destaque = 1 WHERE id_insetos IN(2, 12, 41, 42, 52, 85);
CREATE TABLE habitats (
    id_habitats INT AUTO_INCREMENT PRIMARY KEY,
    nome_habitats VARCHAR(50),
    clima_habitats VARCHAR(50),
    bioma_habitats VARCHAR(50),
    descricao_habitats TEXT
);
TRUNCATE Table insetos;

SELECT * FROM insetos;